Yaml
kepkin/kongctl pull request #2
Opened 2019-06-14 12:30 UTC by mukade1997

Config yaml

2019-06-14 12:45 UTC, kepkin requested changes

2019-06-14 12:45 UTC, kepkin commented on kongctl/__main__.py
> +    YamlConfigResource(httpClient, formatter, 'services').build_parser(config)
спрячь аргумент 'services', там же не предполагаются другие значения.

2019-06-14 12:45 UTC, kepkin commented on kongctl/resources.py
> +        config_obj['services'][-1]['name'] = self.data['service']['id']
в name должно быть имя сервиса а не id

2019-06-14 12:45 UTC, kepkin commented on kongctl/resources.py
> +        config_obj['services'][-1]['url'] = self.data['service']['host']
url должно быть комбинацией scheme + host + port + path

2019-06-14 12:45 UTC, kepkin commented on kongctl/resources.py
> +    def contain_config(self):
вместо [-1] используй append

2019-06-14 12:45 UTC, kepkin commented on kongctl/resources.py
> +    data = dict()
Это ты сделал переменную глобальную для всех инстансов класса. Т.е. будет так:
```
a = YamlConfigResource()
b = YamlConfigResource()

a.data = "trololo"
print(b.data)  #  выведет "trololo"
```

Чтобы у каждого класса был свой data, его нужно инициализировать в конструкторе класса:
```
class YamlConfigResource(..):
     def __init__(self, ...):
          super(...)
          self.data = dict()
```

2019-06-14 12:58 UTC, mukade1997 commented on kongctl/resources.py
> +        config_obj['services'][-1]['url'] = self.data['service']['host']
А где можно взять scheme?

2019-06-14 14:55 UTC, kepkin requested changes

2019-06-14 14:55 UTC, kepkin commented on kongctl/resources.py
> +                         ":" + str(self.data['service']['port'])
У строки есть метод формат, который позволяет удобнее строить строки https://pyformat.info/

``"{protocol}://{host}:{port}{path}".format(**self.data['service'])``

2019-06-14 14:55 UTC, kepkin commented on kongctl/resources.py
> +            service['routes'].append(collections.OrderedDict(name=n['id'], paths=n['paths']))
`append(route)`

2019-06-14 14:55 UTC, kepkin commented on kongctl/resources.py
> +        config = config.set_defaults(func=self.yaml_list)
Добавь здесь описания параметра, чтобы в yaml_list читать его из args а не not_parsed

2019-06-14 14:55 UTC, kepkin commented on kongctl/resources.py
> +    def get_list(self, args, non_parsed, rout_or_plug):
А если бы кроме routes и plugins были ещё 10 разных значений, то имя переменной уместилось бы на экране? Переменные называй по тому, что они символизируют а не по значениям, которые могут принимать.

2019-06-14 14:55 UTC, kepkin commented on kongctl/resources.py
> +        return r.json()
Kong может вернуть слишком много результатов, которые не уместятся в один запрос. Тут надо переиспользовать self._list()

2019-06-14 14:55 UTC, kepkin commented on kongctl/resources.py
> +        self.resource_name = rout_or_plug
Я полчаса втыкал, зачем тебе тут подменивать self.dir и self.resource_name
Лучше создавай объекты RouteResource и PluginResource и вызывай ихний ._list()

2019-06-17 09:57 UTC, kepkin commented on kongctl/resources.py
> +        self.contain_config()
плохое название, не понятно что функция делает из названия.

2019-06-17 10:03 UTC, kepkin requested changes

2019-06-17 10:03 UTC, kepkin commented on kongctl/resources.py
> +        self.data = dict()
Если в рамках одного процесса, вызову два раза .yaml_list для разных сервисов, будет ли у меня правильный вывод?

2019-06-17 10:03 UTC, kepkin commented on kongctl/resources.py
> +    def get_list(self, args, non_parsed, dir):
договаривались dir переименовать в resource_name

2019-06-17 10:28 UTC, kepkin approved these changes

2019-06-17 10:28 UTC, merged